apiVersion: v1
kind: Service
metadata:
  name: bulletin-board-service
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app:   bulletin-board
    slot: {{ .Values.productionSlot }}

